### ISSUE TITLE
What is your current favorite theme?

### ISSUE THREAD

**Issue by azzamsa** [protesilaos/dotfiles#7]
Hi 👋🏽,  

Thank you so much for creating such beautiful themes for Emacs (Modus and Ef).  

As an Elisp beginner, I couldn't find your default theme using [this query](https://github.com/search?q=repo%3Aprotesilaos%2Fdotfiles%20load-theme&type=code).

By the way:  
1. What is your current favorite theme?  
2. If you had to choose one dark theme from Ef-themes, which one would it be?  

Thanks a ton for your huge contribution to community 🥞

**Comment by protesilaos** [comment]
> From: "Azzam S.A" ***@***.***>
> Date: Tue, 26 Nov 2024 23:01:07 -0800
>
> Hi 👋🏽,  

Hello there!

> Thank you so much for creating such beautiful themes for Emacs (Modus and Ef).  

You are welcome!

> As an Elisp beginner, I couldn't find your default theme using [this
> query](https://github.com/search?q=repo%3Aprotesilaos%2Fdotfiles%20load-theme&type=code).

This is because I use the functions that my themes provide to load a
theme. For all my theme-related settings, check this part of my
dotemacs: <https://protesilaos.com/emacs/dotemacs#h:8cf67c82-1ebb-4be8-b0e7-161bbf5419ce>.

> By the way:  
> 1. What is your current favorite theme?  
> 2. If you had to choose one dark theme from Ef-themes, which one would it be?  

I cycle through all my themes. This lets me test them in real-world
situations and determine if I need to make any changes to them.

But if I was forced to use only one theme, it would be 'modus-operandi'.
Add 'modus-vivendi' to have one for the day and one for the night.

> Thanks a ton for your huge contribution to community 🥞 

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by azzamsa** [comment]
Thank you so much for taking the time to reply! 🍩
